apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-validator
  labels:
    app: cat-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-validator
  template:
    metadata:
      labels:
        app: cat-validator
    spec:
      containers:
      - name: cat-validator
        image: cat-validator:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20 